force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>NTF-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/ext_JobId__c.field-meta.xml
<CustomField>
    <fullName>ext_JobId__c</fullName>
    <label>Job Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/txt_Status__c.field-meta.xml
<CustomField>
    <fullName>txt_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MultiCommitCtrl.cls
public with sharing class MultiCommitCtrl {

    // PUBLIC

    @AuraEnabled
    public static void startFlow(){
        try {
            new Flow.Interview.MultiCommit( new Map<String, Object>() ).start();
        }
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    @InvocableMethod(label='Fake Callout' description='Does an HTTP Callout which comes back after n seconds')
    public static List<String> callout(List<Integer> responseWaitSec) {
        List<String> result = new List<String>();

        calloutBackend(responseWaitSec.get(0));

        return result;
    }


    // PRIVATE

    private static void calloutBackend(Integer responseWaitSec) {
        Integer waitForResponse = responseWaitSec * 1000;

        HttpRequest request = new HttpRequest();
        request.setEndpoint('http://slowwly.robertomurray.co.uk/delay/' + waitForResponse + '/url/http://api.copa.do/');
        request.setMethod('GET');
        request.setTimeout(waitForResponse * 2);
        new Http().send(request);

        updateNotificationRecord();
    }

    
    private static void updateNotificationRecord() {
        Notification__c notification = new Notification__c(ext_JobId__c = '1234');
        notification.txt_Status__c = 'Success';
        upsert notification ext_JobId__c;
    }
}