force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>NTF-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/ext_JobId__c.field-meta.xml
<CustomField>
    <fullName>ext_JobId__c</fullName>
    <label>Job Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/txt_JobName__c.field-meta.xml
<CustomField>
    <fullName>txt_JobName__c</fullName>
    <label>Job Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/txt_Status__c.field-meta.xml
<CustomField>
    <fullName>txt_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationReceived__e/NotificationReceived__e.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <pluralLabel>Notifications</pluralLabel>
</CustomObject>

force-app/main/default/objects/NotificationReceived__e/fields/ext_JobId__c.field-meta.xml
<CustomField>
    <fullName>ext_JobId__c</fullName>
    <label>Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationReceived__e/fields/txt_JobName__c.field-meta.xml
<CustomField>
    <fullName>txt_JobName__c</fullName>
    <label>Job Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationReceived__e/fields/txt_Status__c.field-meta.xml
<CustomField>
    <fullName>txt_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BroadcastNotifications.cls
public with sharing class BroadcastNotifications {
    
    private List<Notification__c> notifications;

    
    // CONSTRUCTORS

    public BroadcastNotifications(List<Notification__c> notifications) {
        this.notifications = notifications;
    }


    // PUBLIC

    public void execute() {
        List<NotificationReceived__e> result = new List<NotificationReceived__e>();

        for(Notification__c notification : notifications) {
            result.add( new NotificationReceived__e(ext_JobId__c = notification.ext_JobId__c,
                                                    txt_JobName__c =  notification.txt_JobName__c,
                                                    txt_Status__c = notification.txt_Status__c) );
        }
        
        EventBus.publish(result);
    }
}