force-app/main/default/objects/Event__e/Event__e.object-meta.xml
<CustomObject>
    <label>Event</label>
    <pluralLabel>Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Event__e/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__e/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <label>Topic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DoThisOnEvent.cls
public with sharing class DoThisOnEvent implements Route.Command {
    
    @TestVisible
    private static List<String> called = new List<String>();

    private String publisher;
    private String topic;
    

    // CONSTRUCTOR

    public DoThisOnEvent(String publisher, String topic) {
        this.publisher = publisher;
        this.topic = topic;
    }


    // PUBLIC

    public Boolean matches(Event__e event) {
        return (event.Publisher__c == publisher 
                    && event.Topic__c.startsWith(topic));
    }


    public void execute(Event__e event) {
        called.add(event.Publisher__c + '_' + event.Topic__c);
    }
}