force-app/main/default/objects/Event__e/Event__e.object-meta.xml
<CustomObject>
    <label>Event</label>
    <pluralLabel>Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Event__e/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__e/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <label>Topic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DoThisOnEvent_Test.cls
@IsTest
private class DoThisOnEvent_Test {
    
    @IsTest
    private static void onlyRelevantCalled() {

        // Exercise
        send( new List<Event__e>{ 
                    event('PublisherA', '/topic/1234'),
                    event('PublisherB', '/topic/')
        });


        // Verify
        System.assertEquals(1, DoThisOnEvent.called.size() );
    }
    

    @IsTest
    private static void calledMultipleTimes() {

        // Exercise
        send( new List<Event__e>{
            event('PublisherB', '/topic/'),
            event('PublisherA', '/topic/xyz')
        });

        // Verify
        System.assertEquals(2, DoThisOnEvent.called.size() );
    }
    

    @IsTest
    private static void notCalledWhenNotApplies() {

        // Exercise
        send( new List<Event__e>{ 
            event('PublisherA', '/topic/1234'),
            event('PublisherX', '/topic/')
        });


        // Verify
        System.assert( DoThisOnEvent.called.isEmpty() );
    }


    // HELPER
    
    private static Event__e event(String publisher, String topic) {
        return new Event__e(Publisher__c = publisher, Topic__c = topic);
    }


    private static void send(List<Event__e> events) {
        Test.startTest();

        EventBus.publish(events);
        Test.getEventBus().deliver();

        Test.stopTest();
    }
}