force-app/main/default/objects/TestType__mdt/TestType__mdt.object-meta.xml
<CustomObject>
    <label>Test Type</label>
    <pluralLabel>Test Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/TestType__mdt/fields/UiComponent__c.field-meta.xml
<CustomField>
    <fullName>UiComponent__c</fullName>
    <defaultValue>&quot;DefaultEditor&quot;</defaultValue>
    <label>Edit UI (LWC component)</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestTypesSelector.cls
public with sharing class TestTypesSelector extends fflib_SObjectSelector {

    public Schema.SObjectType getSObjectType() {
        return TestType__mdt.SObjectType;
    }


    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            TestType__mdt.Id,
            TestType__mdt.DeveloperName,
            TestType__mdt.Label,
            TestType__mdt.RunOn__c,
            TestType__mdt.UiComponent__c
        };
    }


    public List<TestType__mdt> byName(String developerName) {
        return (List<TestType__mdt>) Database.query( newQueryFactory()
                                    .setCondition('DeveloperName = :developerName')
                                    .toSOQL() );
    }
}