force-app/main/default/objects/Test__c/Test__c.object-meta.xml
<CustomObject>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test__c/fields/pkl_Status__c.field-meta.xml
<CustomField>
    <fullName>pkl_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test__c/fields/txl_Payload__c.field-meta.xml
<CustomField>
    <fullName>txl_Payload__c</fullName>
    <label>Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QualityGateTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/QualityGateTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PMD</fullName>
    </customValue>
    <customValue>
        <fullName>CodeScan</fullName>
    </customValue>
    <customValue>
        <fullName>Clayton</fullName>
    </customValue>
    <customValue>
        <fullName>Manual</fullName>
    </customValue>
    <masterLabel>Quality Gate Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestsSelector.cls
public class TestsSelector extends fflib_SObjectSelector {
	
	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			Test__c.Id,
			Test__c.Name,
			Test__c.Type__c,
			Test__c.AcceptanceCriteria__c,
            Test__c.txl_Payload__c,
			Test__c.pkl_Status__c
		};
	}


	public Schema.SObjectType getSObjectType() {
		return Test__c.sObjectType;
	}


	public List<Test__c> byId(Set<Id> ids){
		return (List<Test__c>) selectSObjectsById(ids);
	}
}