force-app/main/default/objects/Test__c/Test__c.object-meta.xml
<CustomObject>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QualityGateTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TestType__mdt/TestType__mdt.object-meta.xml
<CustomObject>
    <label>Test Type</label>
    <pluralLabel>Test Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/TestType__mdt/fields/UiComponent__c.field-meta.xml
<CustomField>
    <fullName>UiComponent__c</fullName>
    <defaultValue>&quot;DefaultEditor&quot;</defaultValue>
    <label>Edit UI (LWC component)</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/QualityGateTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PMD</fullName>
    </customValue>
    <customValue>
        <fullName>CodeScan</fullName>
    </customValue>
    <customValue>
        <fullName>Clayton</fullName>
    </customValue>
    <customValue>
        <fullName>Manual</fullName>
    </customValue>
    <masterLabel>Quality Gate Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestCtrl.cls
public with sharing class TestCtrl {

    @AuraEnabled
    public static String getComponentForRecord(Id recordId) {
        String result = null;

        try {
            Test__c record = new TestsSelector().byId(new Set<Id>{ recordId })[0];
            TestType__mdt type = new TestTypesSelector().byName(record.Type__c)[0];
            
            result= type.UiComponent__c;
        }
        catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }

        return result;
    }
}