force-app/main/default/objects/DynamicUi__mdt/DynamicUi__mdt.object-meta.xml
<CustomObject>
    <label>Dynamic Ui</label>
    <pluralLabel>Dynamic Ui</pluralLabel>
</CustomObject>

force-app/main/default/objects/DynamicUi__mdt/fields/UiApiName__c.field-meta.xml
<CustomField>
    <fullName>UiApiName__c</fullName>
    <label>UI API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DynamicUi__mdt/fields/UiLocation__c.field-meta.xml
<CustomField>
    <fullName>UiLocation__c</fullName>
    <label>Ui Location</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DynamicUi__mdt/fields/UiType__c.field-meta.xml
<CustomField>
    <fullName>UiType__c</fullName>
    <label>UI Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aura</fullName>
                <default>true</default>
                <label>Aura</label>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Screen Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DynamicUiCtrl.cls
public with sharing class DynamicUiCtrl {

    @AuraEnabled
    public static Component getUiComponent(Id recordId, String uiLocation) {
        DynamicUi__mdt ui = [SELECT UiApiName__c, UiType__c FROM DynamicUi__mdt 
                             WHERE UiLocation__c = :uiLocation LIMIT 1];

        Component result = new Component();
        result.type = ui.UiType__c;
        result.fqName = ui.UiApiName__c;
        return result;
    }


    // INNER

    public class Component {
        @AuraEnabled public String type;
        @AuraEnabled public String fqName;
    }
}