force-app/main/default/objects/DynamicUi__mdt/DynamicUi__mdt.object-meta.xml
<CustomObject>
    <label>Dynamic Ui</label>
    <pluralLabel>Dynamic Ui</pluralLabel>
</CustomObject>

force-app/main/default/objects/DynamicUi__mdt/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>Record Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DynamicUi__mdt/fields/UiApiName__c.field-meta.xml
<CustomField>
    <fullName>UiApiName__c</fullName>
    <label>UI API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test__c/Test__c.object-meta.xml
<CustomObject>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QualityGateTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/QualityGateTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PMD</fullName>
    </customValue>
    <customValue>
        <fullName>CodeScan</fullName>
    </customValue>
    <customValue>
        <fullName>Clayton</fullName>
    </customValue>
    <customValue>
        <fullName>Manual</fullName>
    </customValue>
    <masterLabel>Quality Gate Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DynamicFlowCtrl.cls
public with sharing class DynamicFlowCtrl {

    @AuraEnabled
    public static String getFlowName(Id recordId, String flowType) {
        String result = null;

        try {
            System.debug(LoggingLevel.ERROR, recordId);
            Test__c record = [SELECT Id, Type__c FROM Test__c WHERE Id = :recordId];
            System.debug(LoggingLevel.ERROR, record);
            DynamicUi__mdt ui = [SELECT UiApiName__c FROM DynamicUi__mdt WHERE RecordType__c = :record.Type__c LIMIT 1];
            System.debug(LoggingLevel.ERROR, ui);
            result = ui.UiApiName__c;
        }
        catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }

        return result;
    }
}